import type { IconType } from "react-icons";
import {
  LuArchive,
  LuBan,
  LuBed,
  LuBookOpen,
  LuBriefcase,
  LuCamera,
  LuCarTaxiFront,
  LuChartBar,
  LuCheck,
  LuCircleCheck,
  LuClipboardList,
  LuClock,
  LuEye,
  LuEyeOff,
  LuHeart,
  LuHourglass,
  LuHouse,
  LuImage,
  LuInfo,
  LuKeyRound,
  LuLandmark,
  LuLayers,
  LuLock,
  LuMap,
  LuMapPin,
  LuMegaphone,
  LuMinus,
  LuPackage,
  LuPalette,
  LuPartyPopper,
  LuPawPrint,
  LuPencil,
  LuPencilLine,
  LuPlane,
  LuPlus,
  LuPuzzle,
  LuReceipt,
  LuRuler,
  LuSearch,
  LuSettings,
  LuShare,
  LuShield,
  LuShirt,
  LuShoppingBag,
  LuShoppingCart,
  LuShowerHead,
  LuSparkles,
  LuStar,
  LuStore,
  LuTag,
  LuTimer,
  LuTrash2,
  LuTriangleAlert,
  LuUser,
  LuUsers,
  LuUtensils,
  LuWashingMachine,
  LuX,
} from "react-icons/lu";

// Cada emoji que el panel usaba como ícono, con su equivalente de línea (misma familia que el
// menú lateral y la app de vecinos). Los textos siguen guardando el emoji — por ejemplo en
// `completitudNegocio.ts` o en los estilos de categoría — y se traducen solo al dibujarlo.
const MAPA: Record<string, IconType> = {
  "⚠": LuTriangleAlert,
  "🖼": LuImage,
  "✅": LuCircleCheck,
  "🔍": LuSearch,
  "🔎": LuSearch,
  "✕": LuX,
  "🏪": LuStore,
  "📍": LuMapPin,
  "⏳": LuHourglass,
  "✓": LuCheck,
  "🗑": LuTrash2,
  "✨": LuSparkles,
  "🏷": LuTag,
  "📢": LuMegaphone,
  "📣": LuMegaphone,
  "★": LuStar,
  "⭐": LuStar,
  "☆": LuStar,
  "👤": LuUser,
  "🗂": LuLayers,
  "🎨": LuPalette,
  "🤍": LuHeart,
  "❤": LuHeart,
  "📤": LuShare,
  "📋": LuClipboardList,
  "🕒": LuClock,
  "⏱": LuTimer,
  "📷": LuCamera,
  "🍽": LuUtensils,
  "👁": LuEye,
  "🙈": LuEyeOff,
  "➕": LuPlus,
  "➖": LuMinus,
  "👥": LuUsers,
  "🗺": LuMap,
  "🔑": LuKeyRound,
  "🏠": LuHouse,
  "⚙": LuSettings,
  "🔒": LuLock,
  "🏛": LuLandmark,
  "🎉": LuPartyPopper,
  "📝": LuPencilLine,
  "✏": LuPencil,
  "🛏": LuBed,
  "🛍": LuShoppingBag,
  "🛒": LuShoppingCart,
  "✈": LuPlane,
  "🐾": LuPawPrint,
  "🧾": LuReceipt,
  "💼": LuBriefcase,
  "🚕": LuCarTaxiFront,
  "🧩": LuPuzzle,
  "🛡": LuShield,
  "📦": LuPackage,
  "📊": LuChartBar,
  "🧺": LuWashingMachine,
  "👔": LuShirt,
  "🚿": LuShowerHead,
  "📐": LuRuler,
  "📚": LuBookOpen,
  "🗄": LuArchive,
  "🚫": LuBan,
  "ℹ": LuInfo,
};

/** El emoji sin el selector de variación (U+FE0F) que a veces lo acompaña. */
function base(e: string): string {
  return e.replace(/️/g, "").trim();
}

/**
 * Dibuja como ícono de línea un emoji que el panel usaba de ícono. Hereda el color y el tamaño
 * de letra del contenedor (1em). Si el emoji no está en el mapa, lo omite — nunca se ve un
 * emoji suelto en la interfaz.
 */
export function IconoEmoji({ e, className }: { e: string | null | undefined; className?: string }) {
  if (!e) return null;
  const Icono = MAPA[base(e)];
  if (!Icono) return null;
  return <Icono className={className ? `icono-emoji ${className}` : "icono-emoji"} aria-hidden />;
}
