import type { IconType } from "react-icons";
import {
  IoAirplaneOutline,
  IoAppsOutline,
  IoBagHandleOutline,
  IoBandageOutline,
  IoBicycleOutline,
  IoBriefcaseOutline,
  IoBrushOutline,
  IoBusinessOutline,
  IoBusOutline,
  IoCafeOutline,
  IoCalculatorOutline,
  IoCarOutline,
  IoCartOutline,
  IoColorPaletteOutline,
  IoConstructOutline,
  IoCutOutline,
  IoDiamondOutline,
  IoEllipseOutline,
  IoExtensionPuzzleOutline,
  IoEyeOutline,
  IoFastFoodOutline,
  IoFishOutline,
  IoFitnessOutline,
  IoFlashOutline,
  IoGlassesOutline,
  IoHammerOutline,
  IoHomeOutline,
  IoIceCreamOutline,
  IoKeyOutline,
  IoLeafOutline,
  IoLibraryOutline,
  IoMedicalOutline,
  IoMedkitOutline,
  IoMusicalNotesOutline,
  IoNutritionOutline,
  IoPawOutline,
  IoPizzaOutline,
  IoPricetagOutline,
  IoPrintOutline,
  IoPulseOutline,
  IoReceiptOutline,
  IoRestaurantOutline,
  IoSchoolOutline,
  IoShirtOutline,
  IoStarOutline,
  IoStorefrontOutline,
  IoWaterOutline,
  IoWineOutline,
} from "react-icons/io5";

/**
 * Registro explícito (no `import *`) para que Vite pueda eliminar por tree-shaking los miles de
 * íconos de Ionicons que no usamos — un `import *` metía el set completo (~1MB) al bundle.
 */
export const REGISTRO_ICONOS: Record<string, IconType> = {
  "airplane-outline": IoAirplaneOutline,
  "apps-outline": IoAppsOutline,
  "bag-handle-outline": IoBagHandleOutline,
  "bandage-outline": IoBandageOutline,
  "bicycle-outline": IoBicycleOutline,
  "briefcase-outline": IoBriefcaseOutline,
  "brush-outline": IoBrushOutline,
  "business-outline": IoBusinessOutline,
  "bus-outline": IoBusOutline,
  "cafe-outline": IoCafeOutline,
  "calculator-outline": IoCalculatorOutline,
  "car-outline": IoCarOutline,
  "cart-outline": IoCartOutline,
  "color-palette-outline": IoColorPaletteOutline,
  "construct-outline": IoConstructOutline,
  "cut-outline": IoCutOutline,
  "diamond-outline": IoDiamondOutline,
  "ellipse-outline": IoEllipseOutline,
  "extension-puzzle-outline": IoExtensionPuzzleOutline,
  "eye-outline": IoEyeOutline,
  "fast-food-outline": IoFastFoodOutline,
  "fish-outline": IoFishOutline,
  "fitness-outline": IoFitnessOutline,
  "flash-outline": IoFlashOutline,
  "glasses-outline": IoGlassesOutline,
  "hammer-outline": IoHammerOutline,
  "home-outline": IoHomeOutline,
  "ice-cream-outline": IoIceCreamOutline,
  "key-outline": IoKeyOutline,
  "leaf-outline": IoLeafOutline,
  "library-outline": IoLibraryOutline,
  "medical-outline": IoMedicalOutline,
  "medkit-outline": IoMedkitOutline,
  "musical-notes-outline": IoMusicalNotesOutline,
  "nutrition-outline": IoNutritionOutline,
  "paw-outline": IoPawOutline,
  "pizza-outline": IoPizzaOutline,
  "pricetag-outline": IoPricetagOutline,
  "print-outline": IoPrintOutline,
  "pulse-outline": IoPulseOutline,
  "receipt-outline": IoReceiptOutline,
  "restaurant-outline": IoRestaurantOutline,
  "school-outline": IoSchoolOutline,
  "shirt-outline": IoShirtOutline,
  "star-outline": IoStarOutline,
  "storefront-outline": IoStorefrontOutline,
  "water-outline": IoWaterOutline,
  "wine-outline": IoWineOutline,
};
