import { PlantillaVisual } from "@app-vecinos/tipos";

export const PLANTILLAS_VISUALES: PlantillaVisual[] = [
  {
    id: "lista-simple",
    nombre: "Lista simple",
    modo: "lista",
    origen: "sistema",
    descripcionUso: "El mismo diseño que ya usa hoy el arquetipo Servicios — sin foto, sin destacado.",
    camposEsperados: [
      { etiqueta: "Nombre", tipo: "texto", obligatorio: true },
      { etiqueta: "Detalle", tipo: "texto_largo", obligatorio: false },
      { etiqueta: "Precio", tipo: "precio", obligatorio: true },
    ],
  },
  {
    id: "grilla-foto",
    nombre: "Grilla con foto",
    modo: "lista",
    origen: "sistema",
    descripcionUso: "El mismo diseño que ya usa hoy el arquetipo Catálogo — grilla de 2 columnas con foto y precio.",
    camposEsperados: [
      { etiqueta: "Nombre", tipo: "texto", obligatorio: true },
      { etiqueta: "Precio", tipo: "precio", obligatorio: true },
      { etiqueta: "Sección", tipo: "texto", obligatorio: false },
      { etiqueta: "Foto", tipo: "foto", obligatorio: false },
      { etiqueta: "Destacado", tipo: "booleano", obligatorio: false },
    ],
  },
  {
    id: "lista-agrupada",
    nombre: "Lista agrupada por sección",
    modo: "lista",
    origen: "sistema",
    descripcionUso: "El mismo diseño que ya usa hoy el arquetipo Menú — secciones con insignia \"Más pedido\".",
    camposEsperados: [
      { etiqueta: "Nombre", tipo: "texto", obligatorio: true },
      { etiqueta: "Precio", tipo: "precio", obligatorio: true },
      { etiqueta: "Sección", tipo: "texto", obligatorio: true },
      { etiqueta: "Destacado", tipo: "booleano", obligatorio: false },
    ],
  },
  {
    id: "chips",
    nombre: "Chips",
    modo: "lista",
    origen: "sistema",
    descripcionUso: "El mismo diseño que ya usa hoy el arquetipo Rubros — etiquetas sueltas, sin precio.",
    camposEsperados: [{ etiqueta: "Nombre", tipo: "texto", obligatorio: true }],
  },
  {
    id: "carrusel-descuento",
    nombre: "Carrusel con descuento",
    modo: "lista",
    origen: "sistema",
    descripcionUso: "El mismo diseño que ya usa hoy el arquetipo Ofertas — carrusel horizontal con cinta de descuento.",
    camposEsperados: [
      { etiqueta: "Nombre", tipo: "texto", obligatorio: true },
      { etiqueta: "Precio", tipo: "precio", obligatorio: true },
      { etiqueta: "Precio anterior", tipo: "precio", obligatorio: false },
      { etiqueta: "Etiqueta", tipo: "texto", obligatorio: false },
    ],
  },
  {
    id: "ficha-perfil",
    nombre: "Ficha de perfil",
    modo: "unico",
    origen: "nueva",
    descripcionUso: "Ideal para Consultorías y profesionales independientes — foto, especialidad y tarifa.",
    camposEsperados: [
      { etiqueta: "Foto", tipo: "foto", obligatorio: false },
      { etiqueta: "Especialidad", tipo: "texto", obligatorio: true },
      { etiqueta: "Tarifa", tipo: "precio", obligatorio: true },
      { etiqueta: "Disponible ahora", tipo: "booleano", obligatorio: false },
    ],
  },
  {
    id: "galeria-descripcion",
    nombre: "Galería con descripción",
    modo: "lista",
    origen: "nueva",
    descripcionUso: "Para Inmobiliaria y Turismo — más espacio que la grilla chica de Catálogo.",
    camposEsperados: [
      { etiqueta: "Foto", tipo: "foto", obligatorio: false },
      { etiqueta: "Título", tipo: "texto", obligatorio: true },
      { etiqueta: "Descripción", tipo: "texto_largo", obligatorio: false },
      { etiqueta: "Precio", tipo: "precio", obligatorio: true },
    ],
  },
  {
    id: "tabla-planes",
    nombre: "Tabla de planes",
    modo: "lista",
    origen: "nueva",
    descripcionUso: "Para servicios con paquetes básico/pro/premium — algo que ningún arquetipo actual resuelve bien.",
    camposEsperados: [
      { etiqueta: "Nombre del plan", tipo: "texto", obligatorio: true },
      { etiqueta: "Precio", tipo: "precio", obligatorio: true },
      { etiqueta: "Incluye", tipo: "texto_largo", obligatorio: false },
      { etiqueta: "Recomendado", tipo: "booleano", obligatorio: false },
    ],
  },
  {
    id: "franjas-horarias",
    nombre: "Franjas horarias",
    modo: "lista",
    origen: "nueva",
    descripcionUso: "Para canchas, salas o consultorios que se reservan por horario.",
    camposEsperados: [
      { etiqueta: "Nombre del recurso", tipo: "texto", obligatorio: true },
      { etiqueta: "Precio por hora", tipo: "precio", obligatorio: true },
      { etiqueta: "Disponible", tipo: "booleano", obligatorio: false },
    ],
  },
  {
    id: "ficha-mapa",
    nombre: "Ficha con mapa",
    modo: "lista",
    origen: "nueva",
    descripcionUso: "Versión especializada de Inmobiliaria, con specs propias del rubro (dormitorios, baños, área).",
    camposEsperados: [
      { etiqueta: "Ubicación", tipo: "texto", obligatorio: true },
      { etiqueta: "Dormitorios", tipo: "numero", obligatorio: false },
      { etiqueta: "Baños", tipo: "numero", obligatorio: false },
      { etiqueta: "Área (m²)", tipo: "numero", obligatorio: false },
      { etiqueta: "Precio", tipo: "precio", obligatorio: true },
    ],
  },
  {
    id: "pizarra-precios",
    nombre: "Pizarra de precios",
    modo: "lista",
    origen: "nueva",
    descripcionUso: "Estilo audaz para barberías o food trucks — tipografía grande en vez de lista chica.",
    camposEsperados: [
      { etiqueta: "Nombre", tipo: "texto", obligatorio: true },
      { etiqueta: "Precio", tipo: "precio", obligatorio: true },
    ],
  },
  {
    id: "tarjeta-calificacion",
    nombre: "Tarjeta con calificación",
    modo: "lista",
    origen: "nueva",
    descripcionUso: "Preparada para cuando exista el sistema de reseñas del roadmap.",
    camposEsperados: [
      { etiqueta: "Nombre", tipo: "texto", obligatorio: true },
      { etiqueta: "Precio", tipo: "precio", obligatorio: true },
      { etiqueta: "Calificación", tipo: "numero", obligatorio: false },
    ],
  },
  {
    id: "grid-iconos",
    nombre: "Grid de íconos",
    modo: "lista",
    origen: "nueva",
    descripcionUso: "Un paso más grande y visual que Chips — para Otros servicios y rubros variados.",
    camposEsperados: [
      { etiqueta: "Nombre", tipo: "texto", obligatorio: true },
      { etiqueta: "Ícono", tipo: "texto", obligatorio: false },
    ],
  },
  {
    id: "info-reserva",
    nombre: "Info de contacto y reserva",
    modo: "unico",
    origen: "nueva",
    descripcionUso: "Para negocios simples que solo necesitan decir \"así me contactas\" — sin lista de nada.",
    camposEsperados: [
      { etiqueta: "Cómo llegar", tipo: "texto_largo", obligatorio: false },
      { etiqueta: "Notas", tipo: "texto_largo", obligatorio: false },
      { etiqueta: "Botón de acción", tipo: "texto", obligatorio: false },
    ],
  },
  {
    id: "ficha-datos",
    nombre: "Ficha de datos",
    modo: "unico",
    origen: "nueva",
    descripcionUso: "Comodín en modo único — filas de etiqueta + valor, sirve para casi cualquier atributo suelto.",
    camposEsperados: [{ etiqueta: "Cualquier campo", tipo: "texto", obligatorio: false }],
  },
];
